const OK = 200;
const ERROR_RESPONSE_BAD_REQUEST = 400;
const ERROR_RESPONSE_UNAUTHORIZED = 401;
const ERROR_RESPONSE_FORBIDDEN = 403;
const ERROR_RESPONSE_NOT_FOUND = 404;
const ERROR_RESPONSE_NOT_ALLOWED= 405;
const ERROR_RESPONSE_RATE_LIMIT = 429;
const ERROR_RESPONSE_INTERNAL_SERVER_ERROR = 500;
const ERROR_RESPONSE_BAD_GATEWAY = 502;
const ERROR_RESPONSE_UNAVAILABLE= 503;
const ERROR_RESPONSE_TIMEOUT = 504;
const ERROR_RESPONSE_HTTP_VERSION_NOT_SUPPORTED = 505;

module.exports = {OK, ERROR_RESPONSE_BAD_GATEWAY, ERROR_RESPONSE_BAD_REQUEST, ERROR_RESPONSE_FORBIDDEN, ERROR_RESPONSE_HTTP_VERSION_NOT_SUPPORTED
, ERROR_RESPONSE_RATE_LIMIT, ERROR_RESPONSE_NOT_ALLOWED, ERROR_RESPONSE_NOT_FOUND, ERROR_RESPONSE_INTERNAL_SERVER_ERROR
,ERROR_RESPONSE_UNAVAILABLE, ERROR_RESPONSE_TIMEOUT, ERROR_RESPONSE_UNAUTHORIZED}

